### ISSUE TITLE
Data receive issue

### ISSUE THREAD

**Issue by jonathand1** [thotro/arduino-dw1000#1]
Hi,
I have two DWM1000 and I'm trying to make them communicate.
But when I send message to the other (with one of your test, like pin pong one), the receiver receives the sent message with a square letter at the end. Next times, only squares are received by the receiver.
Is it an issue you're also experiencing ?
Kind regards.

**Comment by thotro** [comment]
Hi there,

unfortunately yes, I observe the same issue - thanks for pointing out! 
I must have introduced a bug with one of the recent commits, but will come up with a fix shortly!

Cheers, Thomas

**Comment by stackbase** [comment]
Thanks for tout reply.

Do you confirm all inputs are at 3.3V (ground excepted of course) ?
Asking you this question because I dev with à 5V Arduino, and I have to pull down to 3.3 on all pins with resistors, and sometimes I get bad information from Device id and more... Like all data to zero for instance

**Comment by thotro** [comment]
Thanks for your comment! Yes, I primarily use a Pro Mini, one which already operates at 3.3V.

At the moment I have an un-pushed fix for the issue of sometimes reading/receiving bad data - it was a message checksum problem. Though, it still requires some further testing, but should get the driver back on track in a moment.

Thomas
