### ISSUE TITLE
Which code base is recommended?

### ISSUE THREAD

**Issue by abencomo** [thotro/arduino-dw1000#142]
Is Master stable or should we use v0.6 release from July 2015?

BTW, why hasn't new releases been created since then?  Is this project still active?

**Comment by HappyDr0id** [comment]
Yes this project is still active, just look at last commits on the master branch : https://github.com/thotro/arduino-dw1000/commits/master

However I don't know why a new release has not been created since last summer. I can't find any written milestones for next releases. But I personnally use the master branch since quite recent commits have fixed some of my issues.
