### ISSUE TITLE
dwm1000 anchor consumes low current after sometime

### ISSUE THREAD

**Issue by yogeshwaran774** [thotro/arduino-dw1000#266]
i am trying ranging with one anchor and one tag .

the issue is it is getting the range or sometime after that the anchor current consumption is around 40-60ma. but if i check with the pro mini it is working fine.
actually i am checking with pcb for anchor and tag.

after sometime the anchor automatically starts and gets the range from the tag again 1 min later it start consuming less current which i mentioned.

and my configuration is atmega328p, dwm1000, 16 MHZ crystal, 18PF crystal cap and two 10 k for IRQ & reset pin.

i am not performing any sleep function into the anchor but i added deep sleep in the tag.

so do you guys know is there any bits responsible for power and how can i find which bit is locked while the anchor current consume is very low(40-60ma).

**Comment by kuek** [comment]
either software or hardware problem. That hard to guess from remote. If you use Localino hardware or other proven hardware you can be sure the hardware is fine. If you start with your own hardware **and** firmware things get complicated... developing these things is not easy and error prone. Rely on something which you know that it works. otherwise you waste a lot of time.
